- name: Set Director
  block:
    - name: Set nodes to director boot order (Dell)
      shell:
        chdir: "{{ badfish_tempdir.path }}"
        cmd: |
          source {{ badfish_venv }}/bin/activate
          {{ badfish_cmd }}{{ item }} -t director
      register: boot_order
      until: boot_order is succeeded
      retries: 3
      delay: 60
  rescue:
    - name: Rescue - Reset iDRAC - {{ item }}
      shell: |
        sshpass -p "{{ lab_ipmi_password }}" ssh -o StrictHostKeyChecking=no {{ lab_ipmi_user }}@mgmt-{{ item }} "racadm racreset soft -f"

    - pause:
        seconds: 300

    - name: Set nodes to director boot order (Dell)
      shell:
        chdir: "{{ badfish_tempdir.path }}"
        cmd: |
          source {{ badfish_venv }}/bin/activate
          {{ badfish_cmd }}{{ item }} -t director
      register: boot_order_re
      until: boot_order_re is succeeded
      retries: 5
      delay: 60
